<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PayrollRegister extends Model
{
    protected $fillable = [
        'cutoff_id',
        'empnum',
        'empname',
        'annual_salary',
        'monthly_rate',
        'hourly_rate',
        'basic_pay',
        'accountNumber',
        'payrollType',
        'factor',
        'late' ,
        'absent' ,
        'nsdReg' ,
        'ot' ,
        'otAfterReg' ,
        'nsdOt' ,
        'rdReg' ,
        'rdOt' ,
        'rdOtAfterReg' ,
        'nsdRdReg' ,
        'nsdRdOt' ,
        'lhReg' ,
        'lhOt' ,
        'lhOtAfterReg' ,
        'nsdLh' ,
        'nsdLhOt' ,
        'shReg' ,
        'shOt' ,
        'shOtAfterReg' ,
        'nsdSh' ,
        'nsdShOt' ,
            
        'lhrdReg' ,
        'lhrdOt' ,
        'lhrdOtAfterReg' ,
        'nsdLhRd' ,
        'nsdLhRdOt' ,
            
        'shrdReg' ,
        'shrdOt' ,
        'shrdOtAfterReg' ,
        'nsdShRd' ,
        'nsdShRdOt' ,

        'dtrAdjustment' ,
        'otAdjustment' ,
        
        'mealAllowanceAdj' ,
        'uniformClothingAllowance' ,
        'transpoAllowance' ,
        'laundryAllowance' ,
        'busMarshallAllowance' ,
        'monthlyHomeSubsidy' ,
        'cashGift' ,
        'ltiCashAwards' ,
        'gasAllowance' ,
        'medicalAssistance' ,
        'medicalCashAllowance' ,
        'retentionBonus' ,
        'mealOt' ,
        'gross' ,

        'employeeTax' ,
        'sssEmployee' ,
        'sssMpfEe' ,
        'sssEmployer' ,
        'sssMpfEr' ,
        'sssEc' ,
        'philhealthEe' ,
        'philhealthEr' ,
        'pagibigEe' ,
        'pagibigEr' ,
        'employeeSavings' ,
        'HdmfLoanAdj' ,
        'coopLoan' ,
        'sssSalaryLoanAdj' ,
        'taxAdjustment' ,
        'totalDeduction' ,
        'net' ,
        'atm' ,
    ];
}
